
import { GoogleGenAI } from "@google/genai";
import { ImageSize } from "../types";

const apiKey = "AIzaSyDSEzifQdcZ4mReF5Imk1XW0l8g0uxIGEU";

if (!apiKey) {
    console.error("FATAL ERROR: VITE_GEMINI_API_KEY is missing in the .env file");
    alert("FATAL ERROR: La configuración de Gemini AI está incompleta. Las funciones de IA no estarán disponibles.");
} else {
    console.log("API Key cargada");
}

const ai = new GoogleGenAI({ apiKey: apiKey || '' });

// Helper to encode file to base64
export const fileToGenerativePart = async (file: File): Promise<{ inlineData: { data: string; mimeType: string } }> => {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onloadend = () => {
      if (typeof reader.result !== 'string') {
        return reject(new Error("Failed to read file as data URL."));
      }
      const base64String = reader.result;
      const base64Data = base64String.split(',')[1];
      resolve({
        inlineData: {
          data: base64Data,
          mimeType: file.type,
        },
      });
    };
    reader.onerror = (error) => reject(error);
    reader.readAsDataURL(file);
  });
};

/**
 * Chat with Maps Grounding
 * Uses gemini-2.5-flash with googleMaps tool
 */
export const chatWithMaps = async (
  prompt: string
): Promise<{ text: string; sources?: Array<{ uri: string; title: string }> }> => {
  if (!apiKey) throw new Error("Gemini API Key not configured.");
  try {
    const model = 'gemini-2.5-flash';
    
    const response = await ai.models.generateContent({
      model,
      contents: prompt,
      config: {
        tools: [{ googleMaps: {} }],
        systemInstruction: "Eres un asistente de logística y seguridad vial experto para MineConnect SAT. Ayudas a los operadores a encontrar rutas seguras, paradas de descanso y verificar condiciones geográficas. Responde siempre en Español.",
      },
    });

    const text = response.text || "No se pudo generar una respuesta.";
    
    const groundingChunks = response.candidates?.[0]?.groundingMetadata?.groundingChunks;
    const sources: Array<{ uri: string; title: string }> = [];

    if (groundingChunks) {
      groundingChunks.forEach((chunk: any) => {
        if (chunk.web?.uri) {
          sources.push({ uri: chunk.web.uri, title: chunk.web.title || 'Fuente Web' });
        }
        if (chunk.maps?.uri) {
           sources.push({ uri: chunk.maps.uri, title: chunk.maps.title || 'Ubicación en Maps' });
        }
      });
    }

    return { text, sources };

  } catch (error) {
    console.error("Error in chatWithMaps:", error);
    throw new Error("Error communicating with the AI assistant for maps.");
  }
};

/**
 * Edit Image using Text Prompt
 * Uses gemini-2.5-flash-image
 */
export const editImage = async (imageFile: File, prompt: string): Promise<string> => {
  if (!apiKey) throw new Error("Gemini API Key not configured.");
  try {
    const imagePart = await fileToGenerativePart(imageFile);
    
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          imagePart,
          { text: prompt }
        ]
      },
    });

    const parts = response.candidates?.[0]?.content?.parts;
    if (parts) {
      for (const part of parts) {
        if (part.inlineData && part.inlineData.data) {
           return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
        }
      }
    }
    
    throw new Error("The model did not return an image. It may have responded with text instead.");

  } catch (error) {
    console.error("Error editing image:", error);
    throw new Error("Failed to edit image with AI.");
  }
};

/**
 * Generate High Quality Image
 * Uses gemini-3-pro-image-preview
 */
export const generateImage = async (prompt: string, size: ImageSize): Promise<string> => {
  if (!apiKey) throw new Error("Gemini API Key not configured.");
  try {
    const response = await ai.models.generateContent({
      model: 'gemini-3-pro-image-preview',
      contents: {
        parts: [{ text: prompt }]
      },
      config: {
        imageConfig: {
          imageSize: size,
          aspectRatio: "16:9"
        }
      }
    });

    const parts = response.candidates?.[0]?.content?.parts;
    if (parts) {
        for (const part of parts) {
            if (part.inlineData && part.inlineData.data) {
                return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
            }
        }
    }
    throw new Error("No image was generated by the model.");
  } catch (error) {
    console.error("Error generating image:", error);
    throw new Error("Failed to generate image with AI.");
  }
};

